startTime = ('2010', '01', '01')
endTime = ('2018', '12', '31')
journals = [
    ('NATURE REVIEWS DRUG DISCOVERY', startTime, endTime),
    ('NATURE REVIEWS MICROBIOLOGY', startTime, endTime),
    ('NATURE MEDICINE', startTime, endTime),
    ('NATURE REVIEWS GENETICS', startTime, endTime),
    ('NATURE REVIEWS IMMUNOLOGY', startTime, endTime),
    ('Nature Reviews Gastroenterology & Hepatology', startTime, endTime),
    ('CELL', startTime, endTime),
    ('NATURE GENETICS', startTime, endTime),
    ('IMMUNITY', startTime, endTime),
    ('Annual Review of Immunology', startTime, endTime),
    ('Molecular Cancer', startTime, endTime),
    ('CLINICAL MICROBIOLOGY REVIEWS', startTime, endTime),
    ('NATURE IMMUNOLOGY', startTime, endTime),
    ('PHARMACOLOGICAL REVIEWS', startTime, endTime),
    ('JOURNAL OF HEPATOLOGY', startTime, endTime),
    ('LANCET INFECTIOUS DISEASES', startTime, endTime),
    ('Annual Review of Biochemistry', startTime, endTime),
    ('Annual Review of Pathology-Mechanisms of Disease', startTime, endTime),
    ('GUT', startTime, endTime),
    ('GASTROENTEROLOGY', startTime, endTime),
    ('Cell Host & Microbe', startTime, endTime),
    ('DRUG RESISTANCE UPDATES', startTime, endTime),
    ('Lancet Gastroenterology & Hepatology', startTime, endTime),
    ('Signal Transduction and Targeted Therapy', startTime, endTime),
    ('MOLECULAR CELL', startTime, endTime),
    ('Nature Microbiology', startTime, endTime),
    ('Science Immunology', startTime, endTime),
    ('TRENDS IN ECOLOGY & EVOLUTION', startTime, endTime),
    ('HEPATOLOGY', startTime, endTime),
    ('ACTA NEUROPATHOLOGICA', startTime, endTime),
    ('TRENDS IN MICROBIOLOGY', startTime, endTime),
    ('NUCLEIC ACIDS RESEARCH', startTime, endTime),
    ('Annual Review of Genetics', startTime, endTime),
    ('TRENDS IN IMMUNOLOGY', startTime, endTime),
    ('FEMS MICROBIOLOGY REVIEWS', startTime, endTime),
    ('MOLECULAR BIOLOGY AND EVOLUTION', startTime, endTime),
    ('PROGRESS IN LIPID RESEARCH', startTime, endTime),
    ('MOLECULAR PSYCHIATRY', startTime, endTime),
    ('CELL DEATH AND DIFFERENTIATION', startTime, endTime),
    ('Annual Review of Microbiology', startTime, endTime),
    ('ADVANCED DRUG DELIVERY REVIEWS', startTime, endTime),
    ('NATURE STRUCTURAL & MOLECULAR BIOLOGY', startTime, endTime),
    ('Nature Chemical Biology', startTime, endTime),
    ('TRENDS IN PHARMACOLOGICAL SCIENCES', startTime, endTime),
    ('Microbiome', startTime, endTime),
    ('JOURNAL OF EXPERIMENTAL MEDICINE', startTime, endTime),
    ('MOLECULAR ASPECTS OF MEDICINE', startTime, endTime),
    ('Annual Review of Pharmacology and Toxicology', startTime, endTime),
    ('TRENDS IN BIOCHEMICAL SCIENCES', startTime, endTime),
    ('Journal for ImmunoTherapy of Cancer', startTime, endTime),
    ('Annual Review of Food Science and Technology', startTime, endTime),
    ('GENOME BIOLOGY', startTime, endTime),
    ('NATURAL PRODUCT REPORTS', startTime, endTime),
    ('Molecular Plant', startTime, endTime),
    ('ALLERGY', startTime, endTime),
    ('IMMUNOLOGICAL REVIEWS', startTime, endTime),
    ('MEDICINAL RESEARCH REVIEWS', startTime, endTime),
    ('COMPREHENSIVE REVIEWS IN FOOD SCIENCE AND FOOD SAFETY', startTime, endTime),
    ('Lancet HIV', startTime, endTime),
    ('TRENDS IN FOOD SCIENCE & TECHNOLOGY', startTime, endTime),
    ('PHARMACOLOGY & THERAPEUTICS', startTime, endTime),
    ('Advances in Carbohydrate Chemistry and Biochemistry', startTime, endTime),
    ('TRENDS IN MOLECULAR MEDICINE', startTime, endTime),
    ('Annual Review of Nutrition', startTime, endTime),
    ('Redox Biology', startTime, endTime),
    ('Liver Cancer', startTime, endTime),
    ('TRENDS IN GENETICS', startTime, endTime),
    ('EMBO JOURNAL', startTime, endTime),
    ('MATRIX BIOLOGY', startTime, endTime),
    ('Cellular & Molecular Immunology', startTime, endTime),
    ('MOLECULAR THERAPY', startTime, endTime),
    ('Molecular Systems Biology', startTime, endTime),
    ('Acta Pharmaceutica Sinica B', startTime, endTime),
    ('Clinical Gastroenterology and Hepatology', startTime, endTime),
    ('GENES & DEVELOPMENT', startTime, endTime),
    ('PLANT CELL', startTime, endTime),
    ('CRITICAL REVIEWS IN FOOD SCIENCE AND NUTRITION', startTime, endTime),
    ('Cancer Immunology Research', startTime, endTime),
    ('SEMINARS IN IMMUNOLOGY', startTime, endTime),
    ('Genome Medicine', startTime, endTime),
    ('MICROBIOLOGY AND MOLECULAR BIOLOGY REVIEWS', startTime, endTime),
    ('AMERICAN JOURNAL OF HUMAN GENETICS', startTime, endTime),
    ('AMERICAN JOURNAL OF GASTROENTEROLOGY', startTime, endTime),
    ('CURRENT BIOLOGY', startTime, endTime),
    ('JOURNAL OF ALLERGY AND CLINICAL IMMUNOLOGY', startTime, endTime),
    ('BIOCHIMICA ET BIOPHYSICA ACTA-REVIEWS ON CANCER', startTime, endTime),
    ('Cell Systems', startTime, endTime),
    ('ISME Journal', startTime, endTime),
    ('Gut Microbes', startTime, endTime),
    ('ENDOSCOPY', startTime, endTime), ('ONCOGENE', startTime, endTime),
    ('JOURNAL OF CONTROLLED RELEASE', startTime, endTime),
    ('AUTOIMMUNITY REVIEWS', startTime, endTime),
    ('Seminars in Immunopathology', startTime, endTime),
    ('DRUGS', startTime, endTime),
    ('GASTROINTESTINAL ENDOSCOPY', startTime, endTime),
    ('CELLULAR AND MOLECULAR LIFE SCIENCES', startTime, endTime),
    ('Cellular and Molecular Gastroenterology and Hepatology', startTime, endTime),
    ('FOOD HYDROCOLLOIDS', startTime, endTime),
    ('CLINICAL INFECTIOUS DISEASES', startTime, endTime),
    ('Journal of Crohns & Colitis', startTime, endTime),
    ('GENOME RESEARCH', startTime, endTime),
    ('Annual Review of Genomics and Human Genetics', startTime, endTime),
    ('Journal of Allergy and Clinical Immunology-In Practice', startTime, endTime),
    ('CURRENT OPINION IN CHEMICAL BIOLOGY', startTime, endTime),
    ('GENETICS IN MEDICINE', startTime, endTime),
    ('EMBO REPORTS', startTime, endTime),
    ('BRITISH JOURNAL OF PHARMACOLOGY', startTime, endTime),
    ('EXPERIMENTAL AND MOLECULAR MEDICINE', startTime, endTime),
    ('Advances in Nutrition', startTime, endTime),
    ('CLINICAL REVIEWS IN ALLERGY & IMMUNOLOGY', startTime, endTime),
    ('npj Genomic Medicine', startTime, endTime),
    ('JOURNAL OF TRAVEL MEDICINE', startTime, endTime),
    ('ANTIOXIDANTS & REDOX SIGNALING', startTime, endTime),
    ('Journal of Neuroinflammation', startTime, endTime),
    ('JOURNAL OF CLINICAL IMMUNOLOGY', startTime, endTime),
    ('CRITICAL REVIEWS IN BIOCHEMISTRY AND MOLECULAR BIOLOGY', startTime, endTime),
    ('Science Signaling', startTime, endTime),
    ('ALIMENTARY PHARMACOLOGY & THERAPEUTICS', startTime, endTime),
    ('Cell Chemical Biology', startTime, endTime),
    ('OncoImmunology', startTime, endTime),
    ('NEUROPATHOLOGY AND APPLIED NEUROBIOLOGY', startTime, endTime),
    ('CLINICAL MICROBIOLOGY AND INFECTION', startTime, endTime),
    ('PLOS BIOLOGY', startTime, endTime),
    ('Essays in Biochemistry', startTime, endTime),
    ('JOURNAL OF PATHOLOGY', startTime, endTime),
    ('CURRENT OPINION IN MICROBIOLOGY', startTime, endTime),
    ('mBio', startTime, endTime),
    ('NEUROPSYCHOPHARMACOLOGY', startTime, endTime),
    ('DRUG DISCOVERY TODAY', startTime, endTime),
    ('MODERN PATHOLOGY', startTime, endTime),
    ('NUTRITION RESEARCH REVIEWS', startTime, endTime),
    ('BIOINORGANIC CHEMISTRY AND APPLICATIONS', startTime, endTime),
    ('Global Food Security-Agriculture Policy Economics and Environment', startTime, endTime),
    ('GENOMICS PROTEOMICS & BIOINFORMATICS', startTime, endTime),
    ('PHARMACOLOGICAL RESEARCH', startTime, endTime),
    ('Acta Crystallographica Section D-Structural Biology', startTime, endTime),
    ('CYTOKINE & GROWTH FACTOR REVIEWS', startTime, endTime),
    ('CRITICAL REVIEWS IN MICROBIOLOGY', startTime, endTime),
    ('Neurotherapeutics', startTime, endTime),
    ('Frontiers in Immunology', startTime, endTime),
    ('Digestive Endoscopy', startTime, endTime),
    ('JOURNAL OF GASTROENTEROLOGY', startTime, endTime),
    ('FOOD CHEMISTRY', startTime, endTime),
    ('Molecular Autism', startTime, endTime),
    ('CURRENT OPINION IN IMMUNOLOGY', startTime, endTime),
    ('IMMUNOLOGY', startTime, endTime),
    ('FREE RADICAL BIOLOGY AND MEDICINE', startTime, endTime),
    ('Gastric Cancer', startTime, endTime),
    ('Current Neuropharmacology', startTime, endTime),
    ('Inflammation and Regeneration', startTime, endTime),
    ('Journal of Innate Immunity', startTime, endTime),
    ('npj Vaccines', startTime, endTime),
    ('CLINICAL NUTRITION', startTime, endTime),
    ('Mucosal Immunology', startTime, endTime),
    ('Hepatobiliary Surgery and Nutrition', startTime, endTime),
    ('npj Biofilms and Microbiomes', startTime, endTime),
    ('Computational and Structural Biotechnology Journal', startTime, endTime),
    ('BRAIN BEHAVIOR AND IMMUNITY', startTime, endTime),
    ('Microbiology Spectrum', startTime, endTime),
    ('Emerging Microbes & Infections', startTime, endTime),
    ('AMYLOID-JOURNAL OF PROTEIN FOLDING DISORDERS', startTime, endTime),
    ('Cell and Bioscience', startTime, endTime),
    ('NUTRITION REVIEWS', startTime, endTime),
    ('Genes & Diseases', startTime, endTime),
    ('JOURNAL OF AUTOIMMUNITY', startTime, endTime),
    ('Molecular Ecology Resources', startTime, endTime),
    ('Journal of Integrative Plant Biology', startTime, endTime),
    ('AMERICAN JOURNAL OF CLINICAL NUTRITION', startTime, endTime),
    ('Journal of Hepato-Biliary-Pancreatic Sciences', startTime, endTime),
    ('BIOMACROMOLECULES', startTime, endTime),
    ('CANCER IMMUNOLOGY IMMUNOTHERAPY', startTime, endTime),
    ('INTERNATIONAL JOURNAL OF BIOLOGICAL MACROMOLECULES', startTime, endTime),
    ('Journal of Inflammation Research', startTime, endTime),
    ('Current Obesity Reports', startTime, endTime),
    ('AMERICAN JOURNAL OF RESPIRATORY CELL AND MOLECULAR BIOLOGY', startTime, endTime),
    ('EXPERT OPINION ON THERAPEUTIC TARGETS', startTime, endTime),
    ('EMERGING INFECTIOUS DISEASES', startTime, endTime),
    ('CLINICAL PHARMACOLOGY & THERAPEUTICS', startTime, endTime),
    ('PLoS Pathogens', startTime, endTime),
    ('International Review of Cell and Molecular Biology', startTime, endTime),
    ('CURRENT OPINION IN STRUCTURAL BIOLOGY', startTime, endTime),
    ('Horticulture Research', startTime, endTime),
    ('CELLULAR ONCOLOGY', startTime, endTime),
    ('PROTEIN SCIENCE', startTime, endTime),
    ('EXPERT OPINION ON THERAPEUTIC PATENTS', startTime, endTime),
    ('Expert Opinion on Drug Delivery', startTime, endTime),
    ('European Heart Journal-Cardiovascular Pharmacotherapy', startTime, endTime),
    ('Asian Journal of Pharmaceutical Sciences', startTime, endTime),
    ('International Journal of Biological Sciences', startTime, endTime),
    ('Frontiers in Nutrition', startTime, endTime),
    ('Clinical Epigenetics', startTime, endTime),
    ('BIOMEDICINE & PHARMACOTHERAPY', startTime, endTime),
    ('BRAIN PATHOLOGY', startTime, endTime),
    ('mSystems', startTime, endTime),
    ('FOOD REVIEWS INTERNATIONAL', startTime, endTime),
    ('FOOD RESEARCH INTERNATIONAL', startTime, endTime),
    ('International Journal of Behavioral Nutrition and Physical Activity', startTime, endTime),
    ('CLINICAL PHARMACOKINETICS', startTime, endTime),
    ('Food Packaging and Shelf Life', startTime, endTime),
    ('DRUG DELIVERY', startTime, endTime),
    ('Open Biology', startTime, endTime),
    ('International Journal of Nanomedicine', startTime, endTime),
    ('Immunity & Ageing', startTime, endTime),
    ('AMERICAN JOURNAL OF SURGICAL PATHOLOGY', startTime, endTime),
    ('PEDIATRIC ALLERGY AND IMMUNOLOGY', startTime, endTime),
    ('MOLECULAR MEDICINE', startTime, endTime),
    ('ANNALS OF ALLERGY ASTHMA & IMMUNOLOGY', startTime, endTime),
    ('Pharmaceutics', startTime, endTime),
    ('JOURNAL OF MEDICAL GENETICS', startTime, endTime),
    ('Antioxidants', startTime, endTime),
    ('EXERCISE IMMUNOLOGY REVIEW', startTime, endTime),
    ('Eurosurveillance', startTime, endTime),
    ('Immune Network', startTime, endTime),
    ('PROCEEDINGS OF THE NUTRITION SOCIETY', startTime, endTime),
    ('JOURNAL OF PHOTOCHEMISTRY AND PHOTOBIOLOGY B-BIOLOGY', startTime, endTime),
    ('Travel Medicine and Infectious Disease', startTime, endTime),
    ('EXPERT OPINION ON INVESTIGATIONAL DRUGS', startTime, endTime),
    ('MOLECULAR ECOLOGY', startTime, endTime),
    ('Clinical & Translational Immunology', startTime, endTime),
    ('ACTA PHARMACOLOGICA SINICA', startTime, endTime),
    ('HUMAN MOLECULAR GENETICS', startTime, endTime),
    ('Clinics in Liver Disease', startTime, endTime),
    ('SEMINARS IN LIVER DISEASE', startTime, endTime),
    ('BIOFACTORS', startTime, endTime),
    ('Expert Opinion on Drug Discovery', startTime, endTime),
    ('Biomedicines', startTime, endTime),
    ('JOURNAL OF FOOD AND DRUG ANALYSIS', startTime, endTime),
    ('Clinical and Molecular Hepatology', startTime, endTime),
    ('JOURNAL OF INFECTION', startTime, endTime),
    ('CRISPR Journal', startTime, endTime),
    ('Circulation-Genomic and Precision Medicine', startTime, endTime),
    ('JOURNAL OF NUTRITIONAL BIOCHEMISTRY', startTime, endTime),
    ('Hepatology International', startTime, endTime),
    ('Current Opinion in Food Science', startTime, endTime),
    ('FOOD AND CHEMICAL TOXICOLOGY', startTime, endTime),
    ('CANCER GENE THERAPY', startTime, endTime),
    ('INFECTIOUS DISEASE CLINICS OF NORTH AMERICA', startTime, endTime),
    ('ANTIVIRAL RESEARCH', startTime, endTime),
    ('JOURNAL OF CLINICAL MICROBIOLOGY', startTime, endTime),
    ('INTERNATIONAL JOURNAL OF MOLECULAR SCIENCES', startTime, endTime),
    ('JOURNAL OF LIPID RESEARCH', startTime, endTime),
    ('PLoS Genetics', startTime, endTime),
    ('Innovative Food Science & Emerging Technologies', startTime, endTime),
    ('MOLECULAR NUTRITION & FOOD RESEARCH', startTime, endTime),
    ('Virulence', startTime, endTime),
    ('PHYTOTHERAPY RESEARCH', startTime, endTime),
    ('INTERNATIONAL JOURNAL OF PHARMACEUTICS', startTime, endTime),
    ('Pharmaceuticals', startTime, endTime),
    ('BIOCHEMICAL PHARMACOLOGY', startTime, endTime),
    ('INTERNATIONAL JOURNAL OF HYGIENE AND ENVIRONMENTAL HEALTH', startTime, endTime),
    ('ALLERGOLOGY INTERNATIONAL', startTime, endTime),
    ('LIVER INTERNATIONAL', startTime, endTime),
    ('Journal of Fungi', startTime, endTime),
    ('Microbial Biotechnology', startTime, endTime),
    ('Frontiers in Pharmacology', startTime, endTime),
    ('BIODRUGS', startTime, endTime),
    ('LIVER TRANSPLANTATION', startTime, endTime),
    ('JOURNAL OF ANTIMICROBIAL CHEMOTHERAPY', startTime, endTime),
    ('PHARMACOPSYCHIATRY', startTime, endTime),
    ('CELLULAR & MOLECULAR BIOLOGY LETTERS', startTime, endTime),
    ('VASCULAR PHARMACOLOGY', startTime, endTime),
    ('Allergy Asthma & Immunology Research', startTime, endTime),
    ('Cannabis and Cannabinoid Research', startTime, endTime),
    ('Disease Models & Mechanisms', startTime, endTime),
    ('Food Engineering Reviews', startTime, endTime),
    ('HELICOBACTER', startTime, endTime),
    ('CNS DRUGS', startTime, endTime),
    ('WORLD JOURNAL OF GASTROENTEROLOGY', startTime, endTime),
    ('BIOLOGY OF BLOOD AND MARROW TRANSPLANTATION', startTime, endTime),
    ('GENOMICS', startTime, endTime), ('Nutrients', startTime, endTime),
    ('THEORETICAL AND APPLIED GENETICS', startTime, endTime),
    ('HUMAN GENE THERAPY', startTime, endTime),
    ('LABORATORY INVESTIGATION', startTime, endTime),
    ('MUTATION RESEARCH-REVIEWS IN MUTATION RESEARCH', startTime, endTime),
    ('Frontiers in Microbiology', startTime, endTime),
    ('Journal of Pathology Clinical Research', startTime, endTime),
    ('Endoscopic Ultrasound', startTime, endTime),
    ('EUROPEAN JOURNAL OF NUTRITION', startTime, endTime),
    ('DRUG SAFETY', startTime, endTime),
    ('EXPERT REVIEWS IN MOLECULAR MEDICINE', startTime, endTime),
    ('CURRENT OPINION IN GENETICS & DEVELOPMENT', startTime, endTime),
    ('EUROPEAN JOURNAL OF PHARMACEUTICS AND BIOPHARMACEUTICS', startTime, endTime),
    ('JOURNAL OF MOLECULAR DIAGNOSTICS', startTime, endTime),
    ('FOOD QUALITY AND PREFERENCE', startTime, endTime),
    ('FOOD CONTROL', startTime, endTime),
    ('CURRENT OPINION IN PHARMACOLOGY', startTime, endTime),
    ('Reviews of Physiology Biochemistry and Pharmacology', startTime, endTime),
    ('FEBS Journal', startTime, endTime),
    ('POSTHARVEST BIOLOGY AND TECHNOLOGY', startTime, endTime),
    ('ARCHIVES OF PATHOLOGY & LABORATORY MEDICINE', startTime, endTime),
    ('EUROPEAN JOURNAL OF IMMUNOLOGY', startTime, endTime),
    ('Genes and Nutrition', startTime, endTime),
    ('FOOD MICROBIOLOGY', startTime, endTime),
    ('ENVIRONMENTAL MICROBIOLOGY', startTime, endTime),
    ('Nucleic Acid Therapeutics', startTime, endTime),
    ('BONE MARROW TRANSPLANTATION', startTime, endTime),
    ('Journal of Oral Microbiology', startTime, endTime),
    ('JOURNAL OF MOLECULAR BIOLOGY', startTime, endTime),
    ('Chinese Medicine', startTime, endTime),
    ('JOURNAL OF IMMUNOLOGY', startTime, endTime),
    ('MICROBIOLOGICAL RESEARCH', startTime, endTime),
    ('BIOCHEMICAL SOCIETY TRANSACTIONS', startTime, endTime),
    ('Food & Function', startTime, endTime),
    ('Journal of the International AIDS Society', startTime, endTime),
    ('BIOELECTROCHEMISTRY', startTime, endTime),
    ('JOURNAL OF NEUROCHEMISTRY', startTime, endTime),
    ('JOURNAL OF FOOD ENGINEERING', startTime, endTime),
    ('PHYTOMEDICINE', startTime, endTime),
    ('INFLAMMATORY BOWEL DISEASES', startTime, endTime),
    ('Infectious Diseases and Therapy', startTime, endTime),
    ('INTERNATIONAL REVIEWS OF IMMUNOLOGY', startTime, endTime),
    ('PATHOLOGY', startTime, endTime),
    ('Frontiers in Cellular and Infection Microbiology', startTime, endTime),
    ('Environmental Microbiome', startTime, endTime),
    ('CANCER CYTOPATHOLOGY', startTime, endTime),
    ('INTERNATIONAL JOURNAL OF ANTIMICROBIAL AGENTS', startTime, endTime),
    ('JOURNAL OF AGRICULTURAL AND FOOD CHEMISTRY', startTime, endTime),
    ('INTERNATIONAL JOURNAL OF FOOD MICROBIOLOGY', startTime, endTime),
    ('BIOORGANIC CHEMISTRY', startTime, endTime),
    ('NEUROPHARMACOLOGY', startTime, endTime),
    ('GENE THERAPY', startTime, endTime),
    ('Frontiers in Molecular Biosciences', startTime, endTime),
    ('CNS Neuroscience & Therapeutics', startTime, endTime),
    ('CHROMOSOME RESEARCH', startTime, endTime),
    ('Microbial Genomics', startTime, endTime),
    ('JOURNAL OF INFECTIOUS DISEASES', startTime, endTime),
    ('EXPERT REVIEW OF MOLECULAR DIAGNOSTICS', startTime, endTime),
    ('Expert Review of Vaccines', startTime, endTime),
    ('MEAT SCIENCE', startTime, endTime),
    ('CHEMICO-BIOLOGICAL INTERACTIONS', startTime, endTime),
    ('FASEB JOURNAL', startTime, endTime),
    ('ANTIMICROBIAL AGENTS AND CHEMOTHERAPY', startTime, endTime),
    ('BIOCHIMICA ET BIOPHYSICA ACTA-MOLECULAR BASIS OF DISEASE', startTime, endTime),
    ('INTERNATIONAL JOURNAL OF NEUROPSYCHOPHARMACOLOGY', startTime, endTime),
    ('Annals of Gastroenterological Surgery', startTime, endTime),
    ('JOURNAL OF BIOLOGICAL CHEMISTRY', startTime, endTime),
    ('Food Science and Human Wellness', startTime, endTime),
    ('Journal of the International Society of Sports Nutrition', startTime, endTime),
    ('IMMUNOLOGY AND CELL BIOLOGY', startTime, endTime),
    ('JOURNAL OF DRUG TARGETING', startTime, endTime),
    ('Marine Drugs', startTime, endTime),
    ('ACS Chemical Biology', startTime, endTime),
    ('Nutrition & Diabetes', startTime, endTime),
    ('INTERNATIONAL JOURNAL OF OBESITY', startTime, endTime),
    ('Expert Review of Anti-Infective Therapy', startTime, endTime),
    ('Therapeutic Advances in Chronic Disease', startTime, endTime),
    ('HISTOPATHOLOGY', startTime, endTime),
    ('Advances in Applied Microbiology', startTime, endTime),
    ('INTERNATIONAL JOURNAL OF BIOCHEMISTRY & CELL BIOLOGY', startTime, endTime),
    ('ACS Infectious Diseases', startTime, endTime),
    ('AIDS PATIENT CARE AND STDS', startTime, endTime),
    ('Hepatology Communications', startTime, endTime),
    ('Current HIV/AIDS Reports', startTime, endTime),
    ('npj Science of Food', startTime, endTime),
    ('PROGRESS IN NEURO-PSYCHOPHARMACOLOGY & BIOLOGICAL PSYCHIATRY', startTime, endTime),
    ('JOURNAL OF ENZYME INHIBITION AND MEDICINAL CHEMISTRY', startTime, endTime),
    ('Expert Review of Clinical Pharmacology', startTime, endTime),
    ('LIFE SCIENCES', startTime, endTime),
    ('MOLECULES AND CELLS', startTime, endTime),
    ('Biology of Sex Differences', startTime, endTime),
    ('CLINICAL AND EXPERIMENTAL ALLERGY', startTime, endTime),
    ('STRUCTURE', startTime, endTime),
    ('GENES CHROMOSOMES & CANCER', startTime, endTime),
    ('Transboundary and Emerging Diseases', startTime, endTime),
    ('Obesity', startTime, endTime),
    ('Therapeutic Advances in Psychopharmacology', startTime, endTime)
]

# &filter=simsearch1.fha

# 优先级数字越小越大
# priority = {'ElsevierScience':7,
# 			'EuropePubMedCentral':6,
# 			'Nature':4,
# 			'PublicLibraryofScience':3,
# 			'PubMedCentral':5,
# 			'SilverchairInformationSystems':2,
# 			'Wiley':1}
prioritySources = ['HighWire', 'Wiley', 'SilverchairInformationSystems', 'PublicLibraryofScience',
                   'NaturePublishingGroup', 'PubMedCentral', 'EuropePubMedCentral']
# ElsevierScience
# https://pubmed.ncbi.nlm.nih.gov/?term=%28%22Cell%22%5BJournal%5D%29+AND+%28%28%222020%2F01%2F01%22%5BDate+-+Publication%5D+%3A+%222021%2F05%2F01%22%5BDate+-+Publication%5D%29%29&sort=
# print(len(config))
headers = {
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
}


# 分为两部分
# 第一个字典是肠道
# 第二个字典是疾病
vaildWords = [
    {'gut': 1, 'intestinal': 1, 'intestine': 1, 'microbiome/microbe': 0.8, '16s': 0.8, 'metagenome/metagenomics': 0.8,
     'bacterium/bacteria': 0.7, "gastrointestinal": 1}, {'immune': 0.8, 'disease': 0.8, 'cancer/tumour': 0.8}]
vaildWordsList = ['gut', 'intestinal', 'intestine', 'microbiome', 'microbe', '16s', 'metagenome', 'metagenomics',
                  'bacterium', 'bacteria', 'gastrointestinal', 'immune', 'disease', 'cancer', 'tumour']
